name: care_nexus
description: "CareNexus - Smart Healthcare Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.1
  google_generative_ai: ^0.4.7

  # ðŸ”¥ Firebase (MUST be here)
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

# ðŸ”¥ APP ICON CONFIG (ROOT LEVEL)
flutter_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: assets/icons/app_logo.jpg
  image_path: assets/icons/app_logo.jpg

flutter:
  uses-material-design: true

  assets:
    - assets/images/google.jpg
    - assets/icons/app_logo.jpg
